### ISSUE TITLE
Separar BottomSheetDialog de la Actividad

### ISSUE THREAD

**Issue by DavidBarbaran** [DavidBarbaran/wallpapers-app#6]
Se debe trabajar el BottomSheetDialog como un nuevo componente y este mismo debe encargarse de inflar el **layout** correspondiente, este componente debe ubicarse en una carpeta llamada **widget**, haciendo independiente de la atividad de donde se invoque.

**Comment by WilliamDaniel2406** [comment]
Gracias al widget BottomSheetBehavior ,no es necesario crear un clase y hacerlo una actividad independiente , dada la aclaración , doy cerrado este issue.
